/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recrutamento.Visao;

import Recrutamento.Controle.ControleFilial;
import Recrutamento.Controle.ControleLogin;
import Recrutamento.Modelo.ModeloFilial;
import Recrutamento.Modelo.ModeloLogin;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paulo
 */
public class CadUsuarios2 extends javax.swing.JDialog {
    
    int codniv;
    int codfil;
        
        
        List<ModeloFilial>listaFilial = new ArrayList<>();
        List<ModeloLogin> listaNivel = new ArrayList<>();


    /**
     * Creates new form CadUsuarios2
     */
    public CadUsuarios2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
       ControleFilial cf = new ControleFilial();
       listaFilial = cf.buscarFilial();
       
       setComboFilial();
       preenchetabela();
       
       cmbNivel.setSelectedItem(null);
       cmbFilial.setSelectedItem(null);

    }

    public void setComboFilial() {

        int i = 0;
        cmbFilial.removeAllItems();
        while (i < listaFilial.size()) {
            cmbFilial.addItem(listaFilial.get(i).getApeFil());
            i++;
        }

    
    }
    
    
    public void preenchetabela(){
      
       List<ModeloLogin> Login = Recrutamento.Controle.ControleLogin.getInstancelogin().buscarLogin();

            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("Cod. Usuario");
            modelo.addColumn("Login");
            modelo.addColumn("Senha");
            modelo.addColumn("Nivel");
            modelo.addColumn("Filial");
            
            //modelo.addColumn("Situação");
          
        jtblUsuarios.setModel(modelo);
        jtblUsuarios.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jtblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(85);
        jtblUsuarios.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtblUsuarios.getColumnModel().getColumn(2).setPreferredWidth(100);
        jtblUsuarios.getColumnModel().getColumn(3).setPreferredWidth(50);
        jtblUsuarios.getColumnModel().getColumn(4).setPreferredWidth(60);
        
        
        
      

            int y = 1;
            for (ModeloLogin i : Login) {
                modelo.addRow(new Object[]{i.getCodusu(),i.getUsuario(),i.getSenha(), i.getId_nivel(),i.getFilial() });
                //  jpb1.setValue(y);
                y++;
            }

            jtblUsuarios.removeAll();  // LIMPA O CONTEUDO DA TABELA

            jtblUsuarios.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        cmbFilial = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbNivel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuarios");
        setResizable(false);

        txtId.setEnabled(false);

        jLabel5.setText("Filial:");

        cmbFilial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilialActionPerformed(evt);
            }
        });

        jtblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblUsuarios);

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha:");

        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", " " }));
        cmbNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNivelActionPerformed(evt);
            }
        });

        jLabel3.setText("Nivel:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel4.setText("Cod. Usuário:");

        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel4)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel1)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel2)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel3)
                                        .addGap(4, 4, 4)
                                        .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel5)
                                        .addGap(4, 4, 4)
                                        .addComponent(cmbFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluir))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(cmbFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilialActionPerformed

        int posicao;

        if (cmbFilial.getSelectedIndex() >= 0) {
            posicao = cmbFilial.getSelectedIndex();

            codfil = listaFilial.get(posicao).getCodFil();

    }//GEN-LAST:event_cmbFilialActionPerformed
    }
    
    private void jtblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblUsuariosMouseClicked

        txtId.setText("");
        txtSenha.setText("");
        txtUsuario.setText("");

        int linhaSelecionada = jtblUsuarios.getSelectedRow();

        txtId.setText("" + jtblUsuarios.getValueAt(linhaSelecionada, 0));
        txtUsuario.setText("" + jtblUsuarios.getValueAt(linhaSelecionada, 1));
        txtSenha.setText("" + jtblUsuarios.getValueAt(linhaSelecionada, 2));

        //Encontrando a Posição dentro do List
        int i = 0;

            // while (!listaNivel.get(i).getId_nivel().equals(jtblUsuarios.getValueAt(linhaSelecionada, 2))) {
                 //     i++;
              //   }

         //  cmbNivel.setSelectedIndex(i);

        i = 0;

        while (!listaFilial.get(i).getApeFil().equals(jtblUsuarios.getValueAt(linhaSelecionada, 4))) {
            i++;
        }

        cmbFilial.setSelectedIndex(i);

    }//GEN-LAST:event_jtblUsuariosMouseClicked

    private void cmbNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNivelActionPerformed

        int posicao;

        if (cmbNivel.getSelectedIndex() >= 0) {
            posicao = cmbNivel.getSelectedIndex();

            codniv = listaNivel.get(posicao).getId_nivel();
        }

    }//GEN-LAST:event_cmbNivelActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        String niv = (String) cmbNivel.getSelectedItem();
        int codfilial = codfil;

        int nivel = Integer.parseInt(niv);

        ModeloLogin  ML = new ModeloLogin();
        ML.setUsuario(txtUsuario.getText());
        ML.setSenha(txtSenha.getText());
        ML.setId_nivel(nivel);
        ML.setFilial(codfilial);

        ControleLogin CL = new ControleLogin();
        CL.InsereLogin(ML);

        txtId.setText("");
        txtSenha.setText("");
        txtUsuario.setText("");
        cmbNivel.setSelectedItem(null);
        cmbFilial.setSelectedItem(null);

        preenchetabela();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        txtId.setText("");
        txtSenha.setText("");
        txtUsuario.setText("");
        cmbNivel.setSelectedItem(null);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       
     
        ModeloLogin  ML = new ModeloLogin();
        ML.setCodusu(Integer.parseInt(txtId.getText()));
        

        ControleLogin CL = new ControleLogin();
        CL.ExcluiLogin(ML);

        txtId.setText("");
        txtSenha.setText("");
        txtUsuario.setText("");
        cmbNivel.setSelectedItem(null);
        cmbFilial.setSelectedItem(null);

        preenchetabela();
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        String niv = (String) cmbNivel.getSelectedItem();
        int codfilial = codfil;

        int nivel = Integer.parseInt(niv);

        ModeloLogin  ML = new ModeloLogin();
        ML.setCodusu(Integer.parseInt(txtId.getText()));
        ML.setUsuario(txtUsuario.getText());
        ML.setSenha(txtSenha.getText());
        ML.setId_nivel(nivel);
        ML.setFilial(codfilial);

        ControleLogin CL = new ControleLogin();
        CL.AlteraLogin(ML);

        txtId.setText("");
        txtSenha.setText("");
        txtUsuario.setText("");
        cmbNivel.setSelectedItem(null);
        cmbFilial.setSelectedItem(null);

        preenchetabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadUsuarios2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadUsuarios2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadUsuarios2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUsuarios2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadUsuarios2 dialog = new CadUsuarios2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbFilial;
    private javax.swing.JComboBox<String> cmbNivel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtblUsuarios;
    private javax.swing.JTextField txtId;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
