/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recrutamento.Visao;

import Recrutamento.Controle.ChamaRelatorios;
import Recrutamento.Controle.ControleSelecao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo
 */
public class Principal extends javax.swing.JFrame {

    public static String filial;
   
    
    
    /**
     * Creates new form Principal
     */
    public Principal(String usuario) throws SQLException {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        labelUsuario.setText(usuario);
       
        int nivel=Recrutamento.Controle.ControleLogin.getInstancelogin().buscarNivel(usuario);
        filial=Recrutamento.Controle.ControleLogin.getInstancelogin().buscarFilial(usuario);
       
        
        jlabelFilial.setText(filial);
             
        if(nivel==2){
        
        MenuAbreVaga.setVisible(false);
        JmenuContratacoes.setVisible(false);
        
        }else if(nivel==3){
        
        jMenuPS.setVisible(false);
        jMenuVagas.setVisible(false);
        jMenuCad.setVisible(false);
        
        
        }
        
        }
        
      

    public Principal() {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabelFilial = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCad = new javax.swing.JMenu();
        JMenuEmpresas = new javax.swing.JMenuItem();
        JMenuFiliais = new javax.swing.JMenuItem();
        JMenuUsuarios = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuVagas = new javax.swing.JMenu();
        MenuAbreVaga = new javax.swing.JMenuItem();
        JMenuConsultavagas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuPS = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        JmenuAbreProcesso = new javax.swing.JMenuItem();
        JMenuInsereVaga = new javax.swing.JMenuItem();
        JMenuInsereCandidato = new javax.swing.JMenuItem();
        JmenuConsultaProcesso = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        JmenuContratacoes = new javax.swing.JMenu();
        MenuSolicitar = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        JMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recrutamento e Seleção");

        jToolBar1.setRollover(true);

        jLabel1.setText("Usuario:   ");
        jLabel1.setToolTipText("");
        jToolBar1.add(jLabel1);

        labelUsuario.setText("jLabel2");
        jToolBar1.add(labelUsuario);

        jLabel2.setText("             Filial:     ");
        jToolBar1.add(jLabel2);

        jlabelFilial.setText("       jLabel3");
        jToolBar1.add(jlabelFilial);

        jMenuCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/010-personal data.png"))); // NOI18N
        jMenuCad.setToolTipText("Cadastros");

        JMenuEmpresas.setText("Empresas");
        jMenuCad.add(JMenuEmpresas);

        JMenuFiliais.setText("Filiais");
        JMenuFiliais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuFiliaisActionPerformed(evt);
            }
        });
        jMenuCad.add(JMenuFiliais);

        JMenuUsuarios.setText("Usuários");
        JMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuUsuariosActionPerformed(evt);
            }
        });
        jMenuCad.add(JMenuUsuarios);

        jMenuItem2.setText("Recrutadores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuCad.add(jMenuItem2);

        jMenuItem6.setText("Relatórios");
        jMenuCad.add(jMenuItem6);

        jMenuBar1.add(jMenuCad);

        jMenuVagas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/035-job offer.png"))); // NOI18N
        jMenuVagas.setToolTipText("Vagas");
        jMenuVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVagasActionPerformed(evt);
            }
        });

        MenuAbreVaga.setText("Abrir");
        MenuAbreVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAbreVagaActionPerformed(evt);
            }
        });
        jMenuVagas.add(MenuAbreVaga);

        JMenuConsultavagas.setText("Consultar");
        JMenuConsultavagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuConsultavagasActionPerformed(evt);
            }
        });
        jMenuVagas.add(JMenuConsultavagas);

        jMenu1.setText("Relatórios");

        jMenuItem12.setText("Vagas (Geral)");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuVagas.add(jMenu1);

        jMenuBar1.add(jMenuVagas);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/028-CV.png"))); // NOI18N
        jMenu3.setToolTipText("Currículos");

        jMenuItem4.setText("Cadastrar");
        jMenuItem4.setToolTipText("");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Buscar");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenuPS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/033-headhunter.png"))); // NOI18N
        jMenuPS.setToolTipText("Processos Seletivos");

        jMenu2.setText("Processo");

        JmenuAbreProcesso.setText("Abrir Processo");
        JmenuAbreProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuAbreProcessoActionPerformed(evt);
            }
        });
        jMenu2.add(JmenuAbreProcesso);

        JMenuInsereVaga.setText("Incluir Vagas");
        jMenu2.add(JMenuInsereVaga);

        JMenuInsereCandidato.setText("Incluir Candidatos");
        jMenu2.add(JMenuInsereCandidato);

        jMenuPS.add(jMenu2);

        JmenuConsultaProcesso.setText("Consultar");
        JmenuConsultaProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuConsultaProcessoActionPerformed(evt);
            }
        });
        jMenuPS.add(JmenuConsultaProcesso);

        jMenuItem11.setText("Relatórios");
        jMenuPS.add(jMenuItem11);

        jMenuBar1.add(jMenuPS);

        JmenuContratacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/047-contract.png"))); // NOI18N
        JmenuContratacoes.setToolTipText("Contratações");

        MenuSolicitar.setText("Solicitar");
        MenuSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSolicitarMouseClicked(evt);
            }
        });
        MenuSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSolicitarActionPerformed(evt);
            }
        });
        JmenuContratacoes.add(MenuSolicitar);

        jMenuItem8.setText("Consultar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        JmenuContratacoes.add(jMenuItem8);

        jMenuItem9.setText("Candidatos");
        JmenuContratacoes.add(jMenuItem9);

        jMenuItem10.setText("Quadro Reserva");
        JmenuContratacoes.add(jMenuItem10);

        jMenuBar1.add(JmenuContratacoes);

        JMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/iconfinder_Log Out_27856.png"))); // NOI18N
        JMenuSair.setToolTipText("Sair");
        JMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuSairMouseClicked(evt);
            }
        });
        JMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(JMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuSairActionPerformed
        
        int sair = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION);
        
        if(sair==JOptionPane.YES_OPTION){
        
            System.exit(0);
    }//GEN-LAST:event_JMenuSairActionPerformed
    } 
    private void JMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuSairMouseClicked
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION);
        
        if(sair==JOptionPane.YES_OPTION){
        
            System.exit(0);
      
    }//GEN-LAST:event_JMenuSairMouseClicked
    }
    private void MenuSolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSolicitarMouseClicked
        // TODO add your handling code here:
     /*   
        SolicitarContratacao frm = new SolicitarContratacao();
        frm.setVisible(true);
        */
    }//GEN-LAST:event_MenuSolicitarMouseClicked

    private void MenuSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSolicitarActionPerformed
             
  SolicitarContratacao janela = new SolicitarContratacao(null, true);
  janela.setModal(true);
  janela.show();
    
     
       
    }//GEN-LAST:event_MenuSolicitarActionPerformed

    private void jMenuVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVagasActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenuVagasActionPerformed

    private void MenuAbreVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAbreVagaActionPerformed
        // TODO add your handling code here:
       
        AbreVaga frm = new AbreVaga();
        frm.setVisible(true);
        
        
    }//GEN-LAST:event_MenuAbreVagaActionPerformed

    private void JMenuConsultavagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuConsultavagasActionPerformed
      
        try {
            // TODO add your handling code here:
            
            VagasGeral frm = new VagasGeral();
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
      /*
      Vagas2 janela = null;
        try {
            janela = new Vagas2(null, true);
            janela.setModal(true);
            janela.show();
            
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      */
      
      
    }//GEN-LAST:event_JMenuConsultavagasActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Curriculum2 frm = new Curriculum2();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       
        ChamaRelatorios cr = new ChamaRelatorios();
        cr.relatoriovagasGeral();
        
         
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void JMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuUsuariosActionPerformed
        
        CadUsuarios2 usuarios = new CadUsuarios2(null, true);
        usuarios.setModal(true);
        usuarios.show();
        
    }//GEN-LAST:event_JMenuUsuariosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
        Recrutadores rec = new Recrutadores();
        rec.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void JmenuAbreProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuAbreProcessoActionPerformed

       int sair = JOptionPane.showConfirmDialog(null,"Deseja Iniciar um Processo Seletivo?","Atenção",JOptionPane.YES_NO_OPTION);
        
        if(sair==JOptionPane.YES_OPTION){
            
          //  ControleSelecao cs = new ControleSelecao();
          //  cs.AbreProcesso();
            
            
            AbreProcesso aprocesso = null;        
           try {
               aprocesso = new AbreProcesso(null, true);
           } catch (SQLException ex) {
               Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
           }
            aprocesso.setModal(true);
            aprocesso.show(); 
      
         
         
                  
    }       
        
        
        
    }//GEN-LAST:event_JmenuAbreProcessoActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        
       Vagas2 vg = null;
        try {
            vg = new Vagas2(null, true);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
       vg.setModal(true);
       vg.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void JMenuFiliaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuFiliaisActionPerformed
        
        CadFilial janela = new CadFilial(null, true);
        janela.setModal(true);
        janela.show();
        
    }//GEN-LAST:event_JMenuFiliaisActionPerformed

    private void JmenuConsultaProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuConsultaProcessoActionPerformed
        
            AbreProcesso processo = null;
        try {
            processo = new AbreProcesso(null, true);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
            processo.setModal(true);
            processo.show();
        
    }//GEN-LAST:event_JmenuConsultaProcessoActionPerformed

    
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuConsultavagas;
    private javax.swing.JMenuItem JMenuEmpresas;
    private javax.swing.JMenuItem JMenuFiliais;
    private javax.swing.JMenuItem JMenuInsereCandidato;
    private javax.swing.JMenuItem JMenuInsereVaga;
    private javax.swing.JMenu JMenuSair;
    private javax.swing.JMenuItem JMenuUsuarios;
    private javax.swing.JMenuItem JmenuAbreProcesso;
    private javax.swing.JMenuItem JmenuConsultaProcesso;
    private javax.swing.JMenu JmenuContratacoes;
    private javax.swing.JMenuItem MenuAbreVaga;
    private javax.swing.JMenuItem MenuSolicitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCad;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuPS;
    private javax.swing.JMenu jMenuVagas;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jlabelFilial;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
