/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recrutamento.Visao;

import Recrutamento.Controle.ControleCargo;
import Recrutamento.Controle.ControleRecrutadores;
import Recrutamento.Modelo.ModeloCargo;
import Recrutamento.Modelo.ModeloRecrutadores;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paulo
 */
public class Recrutadores extends javax.swing.JFrame {
    
    int codcar;
    
        
        List<ModeloCargo> listaCargo = new ArrayList<>();

    /**
     * Creates new form Recrutadores
     */
    public Recrutadores() {
        initComponents();
        preenchetabela();
        
        ControleCargo cc = new ControleCargo();
        listaCargo = cc.buscarCargo();
        
        setComboCargo();
        
        cmbCargo.setSelectedItem(null);
    }

    
    
    public void setComboCargo() {

        int i = 0;
        cmbCargo.removeAllItems();
        while (i < listaCargo.size()) {
            cmbCargo.addItem(listaCargo.get(i).getTitCar());
            i++;
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        cmbCargo = new javax.swing.JComboBox<>();
        txtCel = new javax.swing.JFormattedTextField();
        BtnIncluir = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblRecrutadores = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Recrutadores");
        setResizable(false);

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Cargo:");

        jLabel4.setText("Celular:");

        txtCod.setEditable(false);

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCargoActionPerformed(evt);
            }
        });

        try {
            txtCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BtnIncluir.setText("Incluir");
        BtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIncluirActionPerformed(evt);
            }
        });

        BtnAlterar.setText("Alterar");
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        jtblRecrutadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblRecrutadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblRecrutadoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblRecrutadores);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BtnIncluir)
                                .addGap(18, 18, 18)
                                .addComponent(BtnAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(BtnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIncluir)
                    .addComponent(BtnAlterar)
                    .addComponent(BtnExcluir)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCargoActionPerformed
        
        int posicao;

        if (cmbCargo.getSelectedIndex() >= 0) {
            posicao = cmbCargo.getSelectedIndex();

            codcar = listaCargo.get(posicao).getCodCar();
        }
        
    }//GEN-LAST:event_cmbCargoActionPerformed

    private void BtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIncluirActionPerformed
       
        int codcargo = codcar;
                
        ModeloRecrutadores  PC = new ModeloRecrutadores();
        PC.setCodcar(codcargo);
        PC.setNomrec(txtNome.getText());
        PC.setNumcel(txtCel.getText());
        
        ControleRecrutadores CC = new ControleRecrutadores();
        CC.InsereRecrutadores(PC);
        
        
            txtCel.setText("");
            txtCod.setText("");
            txtNome.setText("");
            cmbCargo.setSelectedItem(null);
            
            preenchetabela();
        
    }//GEN-LAST:event_BtnIncluirActionPerformed

    private void jtblRecrutadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblRecrutadoresMouseClicked
        
        txtCel.setText("");
        txtCod.setText("");
        txtNome.setText("");
        cmbCargo.setSelectedItem(null);
        
        

                     
            int linhaSelecionada = jtblRecrutadores.getSelectedRow();

            txtCel.setText("" + jtblRecrutadores.getValueAt(linhaSelecionada, 3));
            txtCod.setText("" + jtblRecrutadores.getValueAt(linhaSelecionada, 0));
            txtNome.setText("" + jtblRecrutadores.getValueAt(linhaSelecionada, 1));
            
            
            //Encontrando a Posição dentro do List
            int i = 0;

            while (!listaCargo.get(i).getTitCar().equals(jtblRecrutadores.getValueAt(linhaSelecionada, 2))) {
                i++;
            }

            cmbCargo.setSelectedIndex(i);

                    
    }//GEN-LAST:event_jtblRecrutadoresMouseClicked

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed

              
        ModeloRecrutadores  PC = new ModeloRecrutadores();
        PC.setCodrec(Integer.parseInt(txtCod.getText()));
        
        
        ControleRecrutadores CC = new ControleRecrutadores();
        CC.ExcluiRecrutadores(PC);
        
        
            txtCel.setText("");
            txtCod.setText("");
            txtNome.setText("");
            cmbCargo.setSelectedItem(null);
            
            preenchetabela();        
               
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        
        int codcargo = codcar;
                
        ModeloRecrutadores  PC = new ModeloRecrutadores();
        PC.setCodrec(Integer.parseInt(txtCod.getText()));
        PC.setCodcar(codcargo);
        PC.setNumcel(txtCel.getText());
        
        ControleRecrutadores CC = new ControleRecrutadores();
        CC.AlteraRecrutadores(PC);
        
        
            txtCel.setText("");
            txtCod.setText("");
            txtNome.setText("");
            cmbCargo.setSelectedItem(null);
            
            preenchetabela();
        
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
            txtCel.setText("");
            txtCod.setText("");
            txtNome.setText("");
            cmbCargo.setSelectedItem(null);
        
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    public void preenchetabela(){
      
       List<ModeloRecrutadores> Recrutadores = Recrutamento.Controle.ControleRecrutadores.getInstancerecrutadores().buscarRecrutadores();

            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("Código");
            modelo.addColumn("Nome");
            modelo.addColumn("Cargo");
            modelo.addColumn("Celular");
            
            
          
        jtblRecrutadores.setModel(modelo);
        jtblRecrutadores.setAutoResizeMode(jtblRecrutadores.AUTO_RESIZE_OFF);
        jtblRecrutadores.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtblRecrutadores.getColumnModel().getColumn(1).setPreferredWidth(150);
        jtblRecrutadores.getColumnModel().getColumn(2).setPreferredWidth(100);
        jtblRecrutadores.getColumnModel().getColumn(3).setPreferredWidth(100);
        
      

            int y = 1;
            for (ModeloRecrutadores i : Recrutadores) {
                modelo.addRow(new Object[]{i.getCodrec(), i.getNomrec(), i.getCargo(), i.getNumcel()});
                //  jpb1.setValue(y);
                y++;
            }

            jtblRecrutadores.removeAll();  // LIMPA O CONTEUDO DA TABELA

            jtblRecrutadores.setModel(modelo);

       
          
      
      
      
      
      }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recrutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recrutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recrutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recrutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recrutadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnIncluir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtblRecrutadores;
    private javax.swing.JFormattedTextField txtCel;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
